spring.application.name=26marSpringbotcrudtrial
spring.datasource.url=jdbc:h2:mem:warehousedb
spring.datasource.driver-class=org.h2.driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

